### ISSUE TITLE
train_letters.py not running

### ISSUE THREAD

**Issue by RaziAhm** [pannous/tensorflow-ocr#10]
Traceback (most recent call last):
  File "train_letters.py", line 61, in <module>
    net.train(data=data, dropout=.6, display_step=10, test_step=1000) # run resume
  File "/usr/local/lib/python3.5/dist-packages/layer/net.py", line 438, in train
    tf.add_check_numerics_ops()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/numerics.py", line 90, in add_check_numerics_ops
    raise ValueError("`tf.add_check_numerics_ops() is not compatible "
ValueError: `tf.add_check_numerics_ops() is not compatible with TensorFlow control flow operations such as `tf.cond()` or `tf.while_loop()`.

**Comment by gewenpulan** [comment]
i met this err too 
my tensorflow version is 1.4.0  i guess use last version is  ok

**Comment by pannous** [comment]
just tried with tensorflow 1.5.0 
 ok

**Comment by Parkwdllcr** [comment]
reinstall!

**Comment by maky-hnou** [comment]
I tried with different versions of Tensorflow including 1.5.0, but I still get the same error:  
```
learning_rate: 0.000300
Traceback (most recent call last):
  File "train_letters.py", line 61, in <module>
    net.train(data=data, dropout=.6, display_step=10, test_step=1000) # run resume
  File "~/.virtualenvs/hocr/lib/python3.6/site-packages/layer/net.py", line 438, in train
    tf.add_check_numerics_ops()
  File "~/.virtualenvs/hocr/lib/python3.6/site-packages/tensorflow/python/ops/numerics.py", line 90, in add_check_numerics_ops
    raise ValueError("`tf.add_check_numerics_ops() is not compatible "
ValueError: `tf.add_check_numerics_ops() is not compatible with TensorFlow control flow operations such as `tf.cond()` or `tf.while_loop()`.
```
