### ISSUE TITLE
where is the data

### ISSUE THREAD

**Issue by gewenpulan** [pannous/tensorflow-ocr#8]
I am running train_letter.py    and return this  "No such file or directory: 'fonts.list'"

**Comment by calicratis19** [comment]
Same question here. Also /data/fonts/ directory missing as well.

**Comment by hbaslan** [comment]
/data/fonts/DroidSans.ttf missing

**Comment by pannous** [comment]
sorry for the very late reply.
 the mechanism to automatically find the fonts was repaired.

**Comment by gewenpulan** [comment]
i am running on windows, the newest version  still not  ok ,  message  :


F:\OCR\tensorflow-ocr-master>python train_letters.py
extensions loaded
using OVERFIT DEBUG DATA!!!
Building fonts.list
'locate' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "train_letters.py", line 4, in <module>
    import letter
  File "F:\OCR\tensorflow-ocr-master\letter.py", line 68, in <module>
    find_fonts()
  File "F:\OCR\tensorflow-ocr-master\letter.py", line 42, in find_fonts
    return readlines("fonts.list")
  File "F:\OCR\tensorflow-ocr-master\extensions.py", line 1400, in readlines
    return list(map(str.strip, open(source).readlines()))
FileNotFoundError: [Errno 2] No such file or directory: 'fonts.list'

and i search this code :
def find_fonts():
	if platform == "darwin":
		os.system("mdfind -name '.ttf' | grep '.ttf$' | iconv -f utf-8 -t ascii  > fonts.list")
	else:
		os.system("locate '.ttf' | grep '.ttf$'  > fonts.list")
	return readlines("fonts.list")

no windows....

**Comment by pannous** [comment]
added windows: `sorry, how do I find fonts on Windows? falling back to Menlo.ttf`
